CATEGORY_SOUNDS = [
    (["funny", "comedy", "lol", "lmao", "rofl", "haha"], "sounds/funny.mp3"),
    (["sad", "cry", "depressed", "depressing"], "sounds/sad.mp3"),
    (["wholesome", "heartwarming", "pure"], "sounds/wholesome.mp3"),
    (["scary", "horror", "creepy", "fear"], "sounds/scary.mp3"),
    (["epic", "action", "legendary", "amazing"], "sounds/epic.mp3"),
    (["fail", "cringe", "embarrassing"], "sounds/fail.mp3"),
    (["cute", "adorable", "animal", "kitten", "puppy"], "sounds/cute.mp3"),
    (
        ["motivational", "inspiring", "inspiration", "success"],
        "sounds/motivational.mp3",
    ),
    (["relatable", "daily", "life", "everyday"], "sounds/relatable.mp3"),
    (["weird", "random", "strange", "bizarre"], "sounds/weird.mp3"),
]

DEFAULT_SOUND = "sounds/relatable.mp3"

YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

WAIT_TIME = 12 * 60 * 60

DEFAULT_TAGS = [
    "discover",
    "viral",
    "explore",
    "foryou",
    "fyp",
    "funny",
    "memes",
    "trend",
    "trending",
    "shorts",
    "lol",
    "comedy",
    "laugh",
    "2025",
    "best",
    "top",
    "new",
    "now",
    "mustsee",
    "wow",
    "amazing",
    "crazy",
    "epic",
    "daily",
    "today",
    "share",
    "like",
    "subscribe",
    "youtube",
    "short",
    "entertainment",
    "internet",
    "video",
    "clip",
    "challenge",
    "reaction",
    "relatable",
    "life",
    "moment",
    "fail",
    "win",
    "omg",
    "haha",
    "rofl",
    "lmao",
    "wtf",
    "cool",
    "awesome",
    "random",
    "memevideo",
    "memepage",
    "memelord",
    "memelife",
    "memedaily",
    "memes2025",
    "explorepage",
    "exploremore",
    "discoverpage",
    "discovermore",
    "viralvideo",
    "viralshorts",
    "viralclips",
    "foryoupage",
    "foryourpage",
    "fypシ",
    "fypage",
    "fypシ゚viral",
    "fypシ゚funny",
    "fypシ゚comedy",
    "fypシ゚trend",
    "fypシ゚lol",
    "fypシ゚memes",
    "fypシ゚2025",
    "fypシ゚best",
    "fypシ゚top",
    "fypシ゚new",
    "fypシ゚now",
    "fypシ゚mustsee",
    "fypシ゚wow",
    "fypシ゚amazing",
    "fypシ゚crazy",
    "fypシ゚epic",
    "fypシ゚daily",
    "fypシ゚today",
    "fypシ゚share",
    "fypシ゚like",
    "fypシ゚subscribe",
    "fypシ゚youtube",
    "fypシ゚short",
    "fypシ゚entertainment",
    "fypシ゚internet",
    "fypシ゚video",
    "fypシ゚clip",
    "fypシ゚challenge",
    "fypシ゚reaction",
    "fypシ゚relatable",
    "fypシ゚life",
    "fypシ゚moment",
    "fypシ゚fail",
    "fypシ゚win",
    "fypシ゚omg",
    "fypシ゚haha",
    "fypシ゚rofl",
    "fypシ゚lmao",
    "fypシ゚wtf",
    "fypシ゚cool",
    "fypシ゚awesome",
    "fypシ゚random",
    "fypシ゚memevideo",
    "fypシ゚memepage",
    "fypシ゚memelord",
    "fypシ゚memelife",
    "fypシ゚memedaily",
    "fypシ゚memes2025",
    "fypシ゚explorepage",
    "fypシ゚exploremore",
    "fypシ゚discoverpage",
    "fypシ゚discovermore",
    "fypシ゚viralvideo",
    "fypシ゚viralshorts",
    "fypシ゚viralclips",
]

REDDIT_MAX_FAIL = 10
